#!/usr/bin/env bash

alias c='cargo'
alias g='git'
alias groot='cd $(git rev-parse --show-toplevel)'
alias xnotify='xmessage -nearmouse -timeout 5 -buttons ""'
alias o='code -r'
alias so='fview -r '
alias vi='vim'
alias vpnd='openvpn3 session-manage -D -c /home/sam/profile-2788.ovpn'
alias vpnu='openvpn3 session-start --config ~/profile-2788.ovpn --timeout 4800'

alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias ,dog='pygmentize -g'
alias ,findregex="find -regextype posix-extended -regex"
alias ,hgroot='cd $(hg root)'
alias ,pyenv='cd ~/repo/python; . python-virtual-env/bin/activate'
alias ,gpull='find . -mindepth 1 -maxdepth 1 -type d -print -exec git -C {} pull \;'
alias ,rg='rg --vimgrep --color=always'
alias ,clang-format='docker run --rm --volume $(pwd):/repo --workdir="/repo" -it clang-format-14 -c "git config --global --add safe.directory /repo && git diff --name-only | xargs clang-format -i"'

function ,cargo-login {
    az account get-access-token --query "join(' ', ['Bearer', accessToken])" --output tsv | cargo login --registry General
}

function ,cargo-test-count {
    cargo test -- --list | awk '/[0-9]+ tests/{sum+=$1}END{print sum}'
}

function warn {
    "$@"
    zenity --info --text="Finished: $*" || true
}

function mk {
    echo "*** STARTING BUILD ***"
    trap 'kill $(jobs -p)' SIGINT
    trap - SIGINT
    nice ionice -c2 -n7 make -j "$(($(nproc)-3))" "$@"
    local error=$?
    xnotify "Build finished: $*" &
    return $error
}

function s {
    SKIP=(/target/ /build/ /test/ /unit/ /unittests/ /stub/ /js/ /svg/)
    nice ionice -n7 rg --vimgrep --color=always "${SKIP[@]/#/-g!*}" "$@"
}

function ,subdirs {
    ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/ /' -e 's/-/|/'
} # use tree instead

function ,replace {
    find ./ -type f -not -path "*/\.*" -exec sed -i -e "s/$1/$2/g" {} \;
} # use fastmod instead

function ,timediff {
    START=$(date +%s%6N)
    ./"$1"
    END=$(date +%s%6N)
    echo "___________________"
    echo
    echo "Total time (in ns): $((END - START))"
}

function ,hgpurge { hg purge --all "$@" && echo "*** PURGE FINISHED ***"; }

function ,mv_to_subfolder {
    find . -mindepth 1 -maxdepth 1 ! -name "$1" -exec mv {} "$1" \;
}

function ,docker_cleanup {
    #sudo docker-latest rm -v $(sudo docker-latest ps -qa --no-trunc --filter "status=exited" 2>/dev/null) 2>/dev/null
    #sudo docker-latest rmi $(sudo docker-latest images --filter "dangling=true" -q --no-trunc 2>/dev/null) 2>/dev/null
    docker ps -qa --no-trunc --filter "status=exited" 2>/dev/null | xargs docker rm -v
    docker images --filter "dangling=true" -q --no-trunc 2>/dev/null | xargs docker rmi
}

function ,size {
    if command -v dust >/dev/null; then
        dust "$@"
    else
        du -h --max-depth=1 "$@" | sort -hr
    fi
}

function define_ls_aliases {
    if command -v exa >/dev/null; then
        alias ls='exa'
        alias ll='exa -lbh --icons --color=auto --group-directories-first'
        alias tree='exa --tree'
    else
        alias ll='ls -halt --color=auto'
    fi

    alias l.='ls -d .*'
    alias l='ls -l'
    alias la='ls -hal'
}

function define_better_buildin_aliases {
    if command -v fd >/dev/null; then
        alias ,find=fd
    fi
    if command -v bat >/dev/null; then
        alias ,cat=bat
    fi
    if command -v dust >/dev/null; then
        alias ,du=dust
    fi
    if command -v rip >/dev/null; then
        alias ,rm=rip
    fi
    if command -v procs >/dev/null; then
        alias ,ps=procs
    fi
    if command -v xcp >/dev/null; then
        alias ,cp=xcp
    elif command -v rsync >/dev/null; then
        alias ,cp="rsync -ah --progress"
        alias ,cp_net="rsync -avz"
    fi
}

# enable completion for aliases example:
# alias container=docker\ container
# complete -F _complete_alias container
[[ $0 == "/bin/bash" ]] && complete -F _complete_alias g # git

define_ls_aliases
define_better_buildin_aliases
