source $HOME/antigen.zsh

command -v starship >/dev/null && eval "$(starship init zsh)"
command -v zoxide >/dev/null && eval "$(zoxide init zsh)"
command -v fuck >/dev/null && eval $(thefuck --alias)

antigen use oh-my-zsh

antigen bundles <<EOBUNDLES
  git
  colored-man-pages
  colorize
  command-not-found
  fasd
  gem
  battery
  rsync
  zsh-users/zsh-autosuggestions
  zsh-users/zsh-syntax-highlighting
  jirutka/zsh-shift-select
  bartboy011/cd-reminder
EOBUNDLES

antigen apply

# Options
setopt CORRECT
setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
unsetopt HIST_IGNORE_DUPS
bindkey -r "^V"

command -v sk > /dev/null && source <(sk --shell zsh)
[[ -d "$HOME/.skim" ]] && for file in $HOME/.skim/*.zsh; do source "$file"; done

# alias container=docker\ container
# complete -F _complete_alias container
[[ $0 == "/bin/bash" ]] && complete -F _complete_alias g # git
