source $HOME/antigen.zsh

command -v starship > /dev/null && eval "$(starship init zsh)"
command -v zoxide > /dev/null && eval "$(zoxide init zsh)"

antigen use oh-my-zsh

antigen bundles <<EOBUNDLES
  git
  colored-man-pages
  colorize
  command-not-found
  fasd
  gem
  battery
  rsync
  zsh-users/zsh-syntax-highlighting
  zsh-users/zsh-autosuggestions
  jirutka/zsh-shift-select
  bartboy011/cd-reminder
EOBUNDLES

antigen apply

# Options
setopt CORRECT
setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
unsetopt HIST_IGNORE_DUPS
bindkey -r "^V"
