#!/usr/bin/env bash

alias notify='xmessage -nearmouse -timeout 5 -buttons ""'

function warn {
    "$@"
    notify "Finished: $*" || true
}

function mk {
    local threads
    threads=$(nproc)
    echo "*** STARTING BUILD ***"
    nice ionice -n7 make -j "${threads}" "$@"
    local error=$?
    notify "Build finished: $*" || true
    return $error
}

function s {
    SKIP=(SST sst unit unittests UT stub IHUB tests)
    nice ionice -n7 rg "${SKIP[@]/#/-g!*}" "$@"
}

function subdirs { ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/ /' -e 's/-/|/'
}

function replace { find ./ -type f -not -path "*/\.*" -exec sed -i -e "s/$1/$2/g" {} \;
}  # use fastmod instead

function timediff {
  START=$(date +%s%6N);
  ./"$1";
  END=$(date +%s%6N);
  echo "___________________"
  echo
  echo "Total time (in ns): $(($END - $START))"
}

function purge { hg purge --all "$@" && echo "*** PURGE FINISHED ***" ;}

function mv_all_to_subfolder {
    find . -mindepth 1 -maxdepth 1 ! -name "$1" -exec mv {} "$1" \;
}

function mkcdir {
    mkdir -p "$1" && cd "$1"
}

function docker_cleanup {
    #sudo docker-latest rm -v $(sudo docker-latest ps -qa --no-trunc --filter "status=exited" 2>/dev/null) 2>/dev/null
    #sudo docker-latest rmi $(sudo docker-latest images --filter "dangling=true" -q --no-trunc 2>/dev/null) 2>/dev/null
    docker rm -v "$(docker ps -qa --no-trunc --filter "status=exited" 2>/dev/null)" 2>/dev/null
    docker rmi "$(docker images --filter "dangling=true" -q --no-trunc 2>/dev/null)" 2>/dev/null
}

function size {
    du -h --max-depth=1 $@ | sort -hr
}

alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias cd1='cd ..'
alias cd2='cd ../..'
alias cd3='cd ../../..'
alias cd4='cd ../../../..'
alias cd5='cd ../../../../..'

alias cp_net="rsync -avz"
alias cp="rsync -ah --progress"
alias dog='pygmentize -g'
alias findregex="find -regextype posix-extended -regex"
alias g=git
alias gpull='find . -mindepth 1 -maxdepth 1 -type d -print -exec git -C {} pull \;'
alias groot='cd $(git rev-parse --show-toplevel)'
alias hgroot='cd $(hg root)'
alias l.='ls -d .*'
alias l='ls -l'
alias la="ls -alh"
alias lgrep="l | grep"
alias ll='ls -halt'
alias llgrep="ll | grep"
alias o='code -r'
alias pyenv='cd ~/repo/python; . python-virtual-env/bin/activate'
alias so='fview -r '
alias vi=vim

which exa > /dev/null 2>&1
if [ $? -eq 0 ]; then
  alias ll='exa -lbh --icons --color=auto --group-directories-first'
else
  alias ll='ls -alh --color=auto'
fi

# enable completion for aliases example:
# alias container=docker\ container
# complete -F _complete_alias container
[[ $0 == "/bin/bash" ]] && complete -F _complete_alias g  # git

