#!/usr/bin/env bash

alias notify='xmessage -nearmouse -timeout 5 -buttons ""'

function warn {
    "$@"
    notify "Finished: $*" || true
}

function cmk {
    local threads
    threads=$(nproc)
    if [ $# -gt 0 ]; then
        local target="--target $1"
        shift 1
    fi
    echo "*** STARTING BUILD ***"
    nice ionice -n7 cmake --build . -j "${threads}" "${target}" "$@"
    local error=$?
    notify "Build finished: $*" || true
    return $error
}

function mk {
    local threads
    threads=$(nproc)
    echo "*** STARTING BUILD ***"
    nice ionice -n7 make -j "${threads}" "$@"
    local error=$?
    notify "Build finished: $*" || true
    return $error
}

function s {
    SKIP=(SST sst unit unittests UT stub IHUB tests)
    nice ionice -n7 rg "${SKIP[@]/#/-g!*}" "$@"
}

function ,subdirs { ls -R | grep ":$" | sed -e 's/:$//' -e 's/[^-][^\/]*\//--/g' -e 's/^/ /' -e 's/-/|/'
}  # use tree instead

function ,replace { find ./ -type f -not -path "*/\.*" -exec sed -i -e "s/$1/$2/g" {} \;
}  # use fastmod instead

function ,timediff {
  START=$(date +%s%6N);
  ./"$1";
  END=$(date +%s%6N);
  echo "___________________"
  echo
  echo "Total time (in ns): $(($END - $START))"
}

function ,hgpurge { hg purge --all "$@" && echo "*** PURGE FINISHED ***" ;}

function ,mv_to_subfolder {
    find . -mindepth 1 -maxdepth 1 ! -name "$1" -exec mv {} "$1" \;
}

function ,docker_cleanup {
    #sudo docker-latest rm -v $(sudo docker-latest ps -qa --no-trunc --filter "status=exited" 2>/dev/null) 2>/dev/null
    #sudo docker-latest rmi $(sudo docker-latest images --filter "dangling=true" -q --no-trunc 2>/dev/null) 2>/dev/null
    docker rm -v "$(docker ps -qa --no-trunc --filter "status=exited" 2>/dev/null)" 2>/dev/null
    docker rmi "$(docker images --filter "dangling=true" -q --no-trunc 2>/dev/null)" 2>/dev/null
}

function ,size {
    if command -v dust > /dev/null; then
        dust
    else
        du -h --max-depth=1 "$@" | sort -hr
    fi
}

function define_ls_aliases {
    if command -v exa > /dev/null; then
        alias ls='exa'
        alias ll='exa -lbh --icons --color=auto --group-directories-first'
        alias tree='exa --tree'
    else
        alias ll='ls -halt --color=auto'
    fi

    alias l.='ls -d .*'
    alias l='ls -l'
    alias la='ls -hal'
}

function define_better_buildin_aliases {
    if command -v fd > /dev/null; then
        alias ,find=fd
    fi
    if command -v bat > /dev/null; then
        alias ,cat=bat
    fi
    if command -v dust > /dev/null; then
        alias ,du=dust
    fi
    if command -v rip > /dev/null; then
        alias ,rm=rip
    fi
    if command -v procs > /dev/null; then
        alias ,ps=procs
    fi
    if command -v xcp > /dev/null; then
        alias ,cp=xcp
    elif command -v rsync > /dev/null; then
        alias ,cp="rsync -ah --progress"
        alias ,cp_net="rsync -avz"
    fi
}

alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias ,dog='pygmentize -g'
alias ,findregex="find -regextype posix-extended -regex"
alias ,hgroot='cd $(hg root)'
alias ,pyenv='cd ~/repo/python; . python-virtual-env/bin/activate'
alias ,gpull='find . -mindepth 1 -maxdepth 1 -type d -print -exec git -C {} pull \;'

alias o='code -r'
alias so='fview -r '
alias vi='vim'
alias g='git'
alias groot='cd $(git rev-parse --show-toplevel)'

# enable completion for aliases example:
# alias container=docker\ container
# complete -F _complete_alias container
[[ $0 == "/bin/bash" ]] && complete -F _complete_alias g  # git

define_ls_aliases
define_better_buildin_aliases
