#!/usr/bin/env bash

source install_helpers.sh

function install_python3()
{
  is_installed python3 && return

  install_tool python3
  install_tool python3-pip

  local python_exes=$(python3 -m site --user-base)
  echo "[[ -d ${python_exes} ]] && export PATH=\"${python_exes}/bin:\$PATH\"" >> $HOME/.zshenv
}


install_python3

pip3 install conan