#!/usr/bin/env bash

source install_helpers.sh
print_commence $BASH_SOURCE

function __add_zsh_to_profile() {
  zsh_path=$(which zsh)

  echo "" >> $HOME/.profile
  echo "# Added by $USER for zsh" >> $HOME/.profile
  echo 'export SHELL=$(which zsh)' >> $HOME/.profile
  echo '[ -z "$ZSH_VERSION" ] && exec $SHELL -l' >> $HOME/.profile

  source $HOME/.profile
}

function __change_shell() {
  [ "$SHELL" == "$(which zsh)" ] && echo -e "zsh is already the default shell" && return
  echo "User shell is not zsh. Changing..."
  if ! chsh -s $(which zsh); then
    echo "Failed with chsh. Setting .profile"
    __add_zsh_to_profile
  fi
}

function __install_antigen() {
  [[ -f $HOME/antigen.zsh ]] && echo -e "antigen is already installed" && return
  echo -e "\nInstalling antigen"
  curl -L git.io/antigen > $HOME/antigen.zsh
}


update_file zshrc $HOME/.zshrc
update_file aliases $HOME/.aliases

install_tool curl
install_tool zsh
__install_antigen
__change_shell
