#!/usr/bin/env bash
# shellcheck source=/dev/null
# shellcheck disable=SC2016

source install_helpers.sh
print_commence "$BASH_SOURCE"

function __install_rust() {
  is_installed cargo && return

  echo -e "\nInstalling rust"
  curl https://sh.rustup.rs -sSf | sh
  echo 'source "$HOME/.cargo/env"' >> "$HOME/.zshenv"
  source "$HOME/.zshenv"
}

__install_rust

[[ -d "$HOME/.cargo" ]] && source "$HOME/.cargo/env"

function __basic_tools {
  cargo install \
    starship \
    ripgrep \
    --locked

  command -v starship > /dev/null && echo 'eval "$(starship init zsh)"' >> "$HOME/.zshrc"
}

function install_all_rust_tools {
  cargo install \
    bat \
    du-dust \
    exa \
    fastmod \
    fd-find \
    procs \
    rm-improved \
    sd \
    tokei \
    topgrade \
    xcp \
    zoxide \
    cargo-audit \
    --locked
 
  command -v zoxide > /dev/null && echo 'eval "$(zoxide init zsh)"' >> "$HOME/.zshrc"
}

rustup component add \
  clippy \
  rustfmt

__basic_tools
