#!/usr/bin/env bash

source install_helpers.sh

os_installer update

source install_powerful_shell

source install_common_tools
source install_rust_tools
source install_ruby_tools
source install_python_tools
