#!/usr/bin/env bash

source install_helpers.sh
print_commence $BASH_SOURCE

function __install_ruby() {
  is_installed ruby && return
  echo -e "\nInstalling ruby"

  local rbenv_dir="$HOME/.rbenv"
  if [[ -d ${rbenv_dir} ]]; then
    git_repo_update ${rbenv_dir}
  else
    git clone https://github.com/rbenv/rbenv.git ${rbenv_dir}
  fi
  echo "[[ -d ${rbenv_dir}/bin ]] && export PATH=\"${rbenv_dir}/bin:\$PATH\"" >> $HOME/.zshenv
  echo 'command -v rbenv > /dev/null && eval "$(rbenv init -)"' >> $HOME/.zshenv

  local ruby_build_dir="${rbenv_dir}/plugins/ruby-build"
  if [[ -d ${ruby_build_dir} ]]; then
    git_repo_update ${ruby_build_dir}
  else
    git clone https://github.com/rbenv/ruby-build.git ${ruby_build_dir}
  fi
  echo "[[ -d ${ruby_build_dir}/bin ]] && export PATH=\"${ruby_build_dir}/bin:\$PATH\"" >> $HOME/.zshenv
  source $HOME/.zshenv

  rbenv install 3.0.1
  rbenv global 3.0.1
  ruby -v
}

install_tool libssl-dev

__install_ruby

gem install colorls
