#!/usr/bin/env bash
# shellcheck source=/dev/null

source install_helpers.sh
print_commence "$BASH_SOURCE"

install_tool git
update_file gitconfig "$HOME/.gitconfig"

install_tool rsync
install_tool vim
install_tool screen
install_tool jq
install_tool cmake
install_tool sshpass
install_tool libssl-dev
install_tool pkg-config
install_tool openssh-client
install_tool build-essential
install_tool llvm
install_tool wget
install_tool meson
