#!/usr/bin/env bash
# shellcheck source=/dev/null
# shellcheck disable=SC2016

source install_helpers.sh
print_commence "$BASH_SOURCE"

function __install_rust() {
  is_installed cargo && return

  echo -e "\nInstalling rust"
  curl https://sh.rustup.rs -sSf | sh

  update_file cargo_config.toml "$HOME/.cargo/config.toml"

  [[ -d "$HOME/.cargo" ]] && source "$HOME/.cargo/env"
}

function __install_binstall() {
  curl -L --proto '=https' --tlsv1.2 -sSf \
    https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh |
    bash
}

__install_rust
__install_binstall

cargo binstall \
  bat \
  cargo-audit \
  cargo-bump \
  cargo-edit \
  cargo-machete \
  cargo-nextest \
  cargo-semver-checks \
  du-dust \
  exa \
  fastmod \
  fd-find \
  grcov \
  procs \
  rm-improved \
  sd \
  tokei \
  topgrade \
  xcp \
  zoxide \
  --locked -y

curl -L "https://github.com/cordx56/rustowl/releases/download/v0.1.3/install.sh" | sh

rustup component add \
  clippy \
  llvm-tools-preview \
  rustfmt
