#!/usr/bin/env bash
# shellcheck source=/dev/null

source install_helpers.sh
print_commence "$BASH_SOURCE"

install_tool git
update_dot_file gitconfig "$HOME/.gitconfig"

install_tool cmake
install_tool code
install_tool fzf
install_tool jq
install_tool llvm
install_tool openssh-client
install_tool pkg-config
install_tool ripgrep
install_tool rsync
install_tool screen
install_tool sshpass
install_tool util-linux-user
install_tool vim
install_tool wget
