#!/usr/bin/env bash

source install_helpers.sh
print_commence $BASH_SOURCE

function install_rust() {
  is_installed cargo && return

  echo -e "\nInstalling rust"
  curl https://sh.rustup.rs -sSf | sh
  echo 'source "$HOME/.cargo/env"' >> $HOME/.zshenv
  echo '[[ -d $HOME/.cargo/bin ]] && export PATH="$HOME/.cargo/bin:$PATH"' >> $HOME/.zshenv
  source $HOME/.zshenv
}


install_rust

cargo install fastmod
cargo install ripgrep
