#!/usr/bin/env bash
# shellcheck source=/dev/null
# shellcheck disable=SC2016

source install_helpers.sh
print_commence "$BASH_SOURCE"

function __add_fish_to_profile() {
  {
    echo ''
    echo "# Added by $USER for fish"
    echo 'export SHELL=$(which fish)'
    echo '[ -z "$FISH_VERSION" ] && exec $SHELL -l'
  } >> "$HOME/.profile"

  chmod 644 "$HOME/.profile"
  source "$HOME/.profile"
}

function __change_shell() {
  [ "$SHELL" == "$(which fish)" ] && echo -e "fish is already the default shell" && return
  echo "User shell is not fish. Changing..."
  if ! chsh -s "$(which fish)"; then
    echo "Failed with chsh. Setting fish to .profile"
    __add_fish_to_profile
  fi
}

function __install_oh_my_zsh() {
  [[ -f "$HOME/.oh-my-zsh/oh-my-zsh.sh" ]] && echo -e "oh-my-zsh is already installed" && return
  echo -e "\nInstalling oh-my-zsh"
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
}

function __install_antigen() {
  [[ -f "$HOME/antigen.zsh" ]] && echo -e "antigen is already installed" && return
  echo -e "\nInstalling antigen"
  curl -L git.io/antigen > "$HOME/antigen.zsh"
}

function __install_fish_config() {
  if [ ! -d "$HOME/.config/fish" ]; then
    mkdir -p "$HOME/.config/fish"
    cp fish_config/* "$HOME/.config/fish/"
  else
    echo -e "fish config already exists, copy fish_config/* to ~/.config/fish/ manually if you want to update"
  fi
}

update_dot_file bashrc "$HOME/.bashrc"
update_dot_file zshrc "$HOME/.zshrc"
update_dot_file zshenv "$HOME/.zshenv"
update_dot_file ssh_agent.sh "$HOME/.ssh_agent.sh"
update_dot_file aliases "$HOME/.aliases"
update_dot_file gitattributes "$HOME/.gitattributes"


install_tool curl
install_tool fish

__install_oh_my_zsh
__install_antigen
__change_shell
__install_fish_config
