#!/usr/bin/env bash
# shellcheck source=/dev/null

source install_helpers.sh

os_installer update

source install_common_tools
source install_powerful_shell
source install_rust_tools
source install_python_tools
